# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createnetwork', '0002_auto_20170220_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkanalysis',
            old_name='text',
            new_name='analysis_description',
        ),
        migrations.RenameField(
            model_name='networkanalysis',
            old_name='title',
            new_name='analysis_title',
        ),
        migrations.RenameField(
            model_name='networkanalysis',
            old_name='gene_text',
            new_name='gene_target',
        ),
        migrations.AddField(
            model_name='networkanalysis',
            name='eQTL',
            field=models.BooleanField(default=True, verbose_name='Include eQTL predictions?'),
        ),
        migrations.AddField(
            model_name='networkanalysis',
            name='email',
            field=models.EmailField(default='jen.wilson521@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkanalysis',
            name='location',
            field=models.CharField(choices=[('BRO', 'Bronx'), ('BRK', 'Brooklyn'), ('QNS', 'Queens'), ('MAN', 'Manhattan'), ('STN', 'Staten Island')], default='no_location', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkanalysis',
            name='threshold',
            field=models.DecimalField(decimal_places=2, default=0.45, max_digits=4, verbose_name='threshold'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='networkanalysis',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
